yaml
name: Bid Monitor Bot

on:
  schedule:
    # UTC 기준 00:00은 한국 시간(KST)으로 월요일 오전 9시입니다.
    - cron: '0 0 * * 1'
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install selenium webdriver-manager

    - name: Run Python script
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PW: ${{ secrets.EMAIL_PW }}
        STARBILL_ID: ${{ secrets.STARBILL_ID }}
        STARBILL_PW: ${{ secrets.STARBILL_PW }}
      # 파일 이름을 main1.py로 수정했습니다.
      run: python main1.py  
