name: Bid Monitor Bot

on:
  schedule:
    - cron: '0 0 * * 1'   # 매주 월요일 09:00(KST)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run Python script
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PW: ${{ secrets.EMAIL_PW }}
          STARBILL_ID: ${{ secrets.STARBILL_ID }}
          STARBILL_PW: ${{ secrets.STARBILL_PW }}
        run: python main.py
